api = "0.8"

[buildpack]
  homepage = "https://github.com/paketo-buildpacks/dotnet-core-aspnet-runtime"
  id = "paketo-buildpacks/dotnet-core-aspnet-runtime"
  keywords = ["dotnet", "ASP.NET", "runtime"]
  name = "Paketo Buildpack for ASP.NET Core Runtime"
  sbom-formats = ["application/vnd.cyclonedx+json", "application/spdx+json", "application/vnd.syft+json"]

  [[buildpack.licenses]]
    type = "Apache-2.0"
    uri = "https://github.com/paketo-buildpacks/dotnet-core-aspnet-runtime/blob/main/LICENSE"

[metadata]
  include-files = ["buildpack.toml", "linux/amd64/bin/build", "linux/amd64/bin/detect", "linux/amd64/bin/run", "linux/arm64/bin/build", "linux/arm64/bin/detect", "linux/arm64/bin/run"]
  pre-package = "./scripts/build.sh --target linux/amd64 --target linux/arm64"

  [[metadata.configurations]]
    build = true
    description = "specify a version of ASP.NET Runtime to use"
    name = "BP_DOTNET_RUNTIME_VERSION"

  [[metadata.configurations]]
    build = true
    description = "set to 'Disable' to prevent ASP.NET version roll-forward"
    name = "BP_DOTNET_ROLL_FORWARD"

  [[metadata.dependencies]]
    arch = "amd64"
    checksum = "sha512:842fb896e6d496875cd6bb6943779ca8a7a9684170d7200b7ab2b53433aa151a9a1800998f9da5582237a690996d8168822e50b8d4be8cf9a512cbe7a2240e88"
    cpe = "cpe:2.3:a:microsoft:.net:8.0.22:*:*:*:*:*:*:*"
    deprecation_date = "2026-11-10T00:00:00Z"
    id = "dotnet-core-aspnet-runtime"
    licenses = ["MIT", "MIT-0"]
    name = "ASP.NET Core Runtime"
    os = "linux"
    purl = "pkg:generic/dotnet-core-aspnet-runtime@8.0.22?checksum=842fb896e6d496875cd6bb6943779ca8a7a9684170d7200b7ab2b53433aa151a9a1800998f9da5582237a690996d8168822e50b8d4be8cf9a512cbe7a2240e88&download_url=https://builds.dotnet.microsoft.com/dotnet/aspnetcore/Runtime/8.0.22/aspnetcore-runtime-8.0.22-linux-x64.tar.gz"
    source = "https://builds.dotnet.microsoft.com/dotnet/aspnetcore/Runtime/8.0.22/aspnetcore-runtime-8.0.22-linux-x64.tar.gz"
    source-checksum = "sha512:842fb896e6d496875cd6bb6943779ca8a7a9684170d7200b7ab2b53433aa151a9a1800998f9da5582237a690996d8168822e50b8d4be8cf9a512cbe7a2240e88"
    stacks = ["*"]
    uri = "https://builds.dotnet.microsoft.com/dotnet/aspnetcore/Runtime/8.0.22/aspnetcore-runtime-8.0.22-linux-x64.tar.gz"
    version = "8.0.22"

  [[metadata.dependencies]]
    arch = "arm64"
    checksum = "sha512:538eb7ce62c77f383606906f38f9aa9911339c2ad4ee849c5fb552491c1bc812492395f2975510eb808410263baf06f0771c7caf0b46695251e6c9273111288f"
    cpe = "cpe:2.3:a:microsoft:.net:8.0.22:*:*:*:*:*:*:*"
    deprecation_date = "2026-11-10T00:00:00Z"
    id = "dotnet-core-aspnet-runtime"
    licenses = ["MIT", "MIT-0"]
    name = "ASP.NET Core Runtime"
    os = "linux"
    purl = "pkg:generic/dotnet-core-aspnet-runtime@8.0.22?checksum=538eb7ce62c77f383606906f38f9aa9911339c2ad4ee849c5fb552491c1bc812492395f2975510eb808410263baf06f0771c7caf0b46695251e6c9273111288f&download_url=https://builds.dotnet.microsoft.com/dotnet/aspnetcore/Runtime/8.0.22/aspnetcore-runtime-8.0.22-linux-arm64.tar.gz"
    source = "https://builds.dotnet.microsoft.com/dotnet/aspnetcore/Runtime/8.0.22/aspnetcore-runtime-8.0.22-linux-arm64.tar.gz"
    source-checksum = "sha512:538eb7ce62c77f383606906f38f9aa9911339c2ad4ee849c5fb552491c1bc812492395f2975510eb808410263baf06f0771c7caf0b46695251e6c9273111288f"
    stacks = ["*"]
    uri = "https://builds.dotnet.microsoft.com/dotnet/aspnetcore/Runtime/8.0.22/aspnetcore-runtime-8.0.22-linux-arm64.tar.gz"
    version = "8.0.22"

  [[metadata.dependencies]]
    arch = "amd64"
    checksum = "sha512:e785fe2a7b06a56a0070862d4fbf41df0e1c04b89a76f4cca2d75de320642274ccc49cdd79dd6d781b504e5631e2f25b0b3566474b9f4b347a929d8b176483de"
    cpe = "cpe:2.3:a:microsoft:.net:8.0.23:*:*:*:*:*:*:*"
    deprecation_date = "2026-11-10T00:00:00Z"
    id = "dotnet-core-aspnet-runtime"
    licenses = ["MIT", "MIT-0"]
    name = "ASP.NET Core Runtime"
    os = "linux"
    purl = "pkg:generic/dotnet-core-aspnet-runtime@8.0.23?checksum=e785fe2a7b06a56a0070862d4fbf41df0e1c04b89a76f4cca2d75de320642274ccc49cdd79dd6d781b504e5631e2f25b0b3566474b9f4b347a929d8b176483de&download_url=https://builds.dotnet.microsoft.com/dotnet/aspnetcore/Runtime/8.0.23/aspnetcore-runtime-8.0.23-linux-x64.tar.gz"
    source = "https://builds.dotnet.microsoft.com/dotnet/aspnetcore/Runtime/8.0.23/aspnetcore-runtime-8.0.23-linux-x64.tar.gz"
    source-checksum = "sha512:e785fe2a7b06a56a0070862d4fbf41df0e1c04b89a76f4cca2d75de320642274ccc49cdd79dd6d781b504e5631e2f25b0b3566474b9f4b347a929d8b176483de"
    stacks = ["*"]
    uri = "https://builds.dotnet.microsoft.com/dotnet/aspnetcore/Runtime/8.0.23/aspnetcore-runtime-8.0.23-linux-x64.tar.gz"
    version = "8.0.23"

  [[metadata.dependencies]]
    arch = "arm64"
    checksum = "sha512:c237c886b328a8b79fa6e341590ec6739325450d3f10be9c26bf908e4e1082b03bdf389ab794318187bb4694f261f87e3d4b466017b21980ffe7b4d70d028bb9"
    cpe = "cpe:2.3:a:microsoft:.net:8.0.23:*:*:*:*:*:*:*"
    deprecation_date = "2026-11-10T00:00:00Z"
    id = "dotnet-core-aspnet-runtime"
    licenses = ["MIT", "MIT-0"]
    name = "ASP.NET Core Runtime"
    os = "linux"
    purl = "pkg:generic/dotnet-core-aspnet-runtime@8.0.23?checksum=c237c886b328a8b79fa6e341590ec6739325450d3f10be9c26bf908e4e1082b03bdf389ab794318187bb4694f261f87e3d4b466017b21980ffe7b4d70d028bb9&download_url=https://builds.dotnet.microsoft.com/dotnet/aspnetcore/Runtime/8.0.23/aspnetcore-runtime-8.0.23-linux-arm64.tar.gz"
    source = "https://builds.dotnet.microsoft.com/dotnet/aspnetcore/Runtime/8.0.23/aspnetcore-runtime-8.0.23-linux-arm64.tar.gz"
    source-checksum = "sha512:c237c886b328a8b79fa6e341590ec6739325450d3f10be9c26bf908e4e1082b03bdf389ab794318187bb4694f261f87e3d4b466017b21980ffe7b4d70d028bb9"
    stacks = ["*"]
    uri = "https://builds.dotnet.microsoft.com/dotnet/aspnetcore/Runtime/8.0.23/aspnetcore-runtime-8.0.23-linux-arm64.tar.gz"
    version = "8.0.23"

  [[metadata.dependencies]]
    arch = "amd64"
    checksum = "sha512:0a3c6a20dd2b00928cd22aca0c99d1ddd36ba93e9909a15097b952b54097e0b817454db7beae482a895d1877c281218fffee0f3f07f6a0cbe521e4c39cda5d4a"
    cpe = "cpe:2.3:a:microsoft:.net:9.0.11:*:*:*:*:*:*:*"
    deprecation_date = "2026-11-10T00:00:00Z"
    id = "dotnet-core-aspnet-runtime"
    licenses = ["MIT", "MIT-0"]
    name = "ASP.NET Core Runtime"
    os = "linux"
    purl = "pkg:generic/dotnet-core-aspnet-runtime@9.0.11?checksum=0a3c6a20dd2b00928cd22aca0c99d1ddd36ba93e9909a15097b952b54097e0b817454db7beae482a895d1877c281218fffee0f3f07f6a0cbe521e4c39cda5d4a&download_url=https://builds.dotnet.microsoft.com/dotnet/aspnetcore/Runtime/9.0.11/aspnetcore-runtime-9.0.11-linux-x64.tar.gz"
    source = "https://builds.dotnet.microsoft.com/dotnet/aspnetcore/Runtime/9.0.11/aspnetcore-runtime-9.0.11-linux-x64.tar.gz"
    source-checksum = "sha512:0a3c6a20dd2b00928cd22aca0c99d1ddd36ba93e9909a15097b952b54097e0b817454db7beae482a895d1877c281218fffee0f3f07f6a0cbe521e4c39cda5d4a"
    stacks = ["*"]
    uri = "https://builds.dotnet.microsoft.com/dotnet/aspnetcore/Runtime/9.0.11/aspnetcore-runtime-9.0.11-linux-x64.tar.gz"
    version = "9.0.11"

  [[metadata.dependencies]]
    arch = "arm64"
    checksum = "sha512:bcf66a56f780b720f663e4f276ebbffeb1f8117523d19fe12c545c53f929ce1036710ba078f3019767ccd19e915dc457d60dad426f926b0be46cef74c01143e8"
    cpe = "cpe:2.3:a:microsoft:.net:9.0.11:*:*:*:*:*:*:*"
    deprecation_date = "2026-11-10T00:00:00Z"
    id = "dotnet-core-aspnet-runtime"
    licenses = ["MIT", "MIT-0"]
    name = "ASP.NET Core Runtime"
    os = "linux"
    purl = "pkg:generic/dotnet-core-aspnet-runtime@9.0.11?checksum=bcf66a56f780b720f663e4f276ebbffeb1f8117523d19fe12c545c53f929ce1036710ba078f3019767ccd19e915dc457d60dad426f926b0be46cef74c01143e8&download_url=https://builds.dotnet.microsoft.com/dotnet/aspnetcore/Runtime/9.0.11/aspnetcore-runtime-9.0.11-linux-arm64.tar.gz"
    source = "https://builds.dotnet.microsoft.com/dotnet/aspnetcore/Runtime/9.0.11/aspnetcore-runtime-9.0.11-linux-arm64.tar.gz"
    source-checksum = "sha512:bcf66a56f780b720f663e4f276ebbffeb1f8117523d19fe12c545c53f929ce1036710ba078f3019767ccd19e915dc457d60dad426f926b0be46cef74c01143e8"
    stacks = ["*"]
    uri = "https://builds.dotnet.microsoft.com/dotnet/aspnetcore/Runtime/9.0.11/aspnetcore-runtime-9.0.11-linux-arm64.tar.gz"
    version = "9.0.11"

  [[metadata.dependencies]]
    arch = "amd64"
    checksum = "sha512:489b8077f2661eaebe421140774b0769519c4963a4bb2fe7d5eff72c99b29a81d5ac6684707449a0ff889a074b6ee58fb4d00a346b859fb75d1d5470e8fb9296"
    cpe = "cpe:2.3:a:microsoft:.net:9.0.12:*:*:*:*:*:*:*"
    deprecation_date = "2026-11-10T00:00:00Z"
    id = "dotnet-core-aspnet-runtime"
    licenses = ["MIT", "MIT-0"]
    name = "ASP.NET Core Runtime"
    os = "linux"
    purl = "pkg:generic/dotnet-core-aspnet-runtime@9.0.12?checksum=489b8077f2661eaebe421140774b0769519c4963a4bb2fe7d5eff72c99b29a81d5ac6684707449a0ff889a074b6ee58fb4d00a346b859fb75d1d5470e8fb9296&download_url=https://builds.dotnet.microsoft.com/dotnet/aspnetcore/Runtime/9.0.12/aspnetcore-runtime-9.0.12-linux-x64.tar.gz"
    source = "https://builds.dotnet.microsoft.com/dotnet/aspnetcore/Runtime/9.0.12/aspnetcore-runtime-9.0.12-linux-x64.tar.gz"
    source-checksum = "sha512:489b8077f2661eaebe421140774b0769519c4963a4bb2fe7d5eff72c99b29a81d5ac6684707449a0ff889a074b6ee58fb4d00a346b859fb75d1d5470e8fb9296"
    stacks = ["*"]
    uri = "https://builds.dotnet.microsoft.com/dotnet/aspnetcore/Runtime/9.0.12/aspnetcore-runtime-9.0.12-linux-x64.tar.gz"
    version = "9.0.12"

  [[metadata.dependencies]]
    arch = "arm64"
    checksum = "sha512:9459fd465ac014188b440e0dd785427e3538224d37578a4734382e2a7069c0d87014eb07e98309386e195b4487536f8d8ccb126f7178f2e2521ac934bf63de6d"
    cpe = "cpe:2.3:a:microsoft:.net:9.0.12:*:*:*:*:*:*:*"
    deprecation_date = "2026-11-10T00:00:00Z"
    id = "dotnet-core-aspnet-runtime"
    licenses = ["MIT", "MIT-0"]
    name = "ASP.NET Core Runtime"
    os = "linux"
    purl = "pkg:generic/dotnet-core-aspnet-runtime@9.0.12?checksum=9459fd465ac014188b440e0dd785427e3538224d37578a4734382e2a7069c0d87014eb07e98309386e195b4487536f8d8ccb126f7178f2e2521ac934bf63de6d&download_url=https://builds.dotnet.microsoft.com/dotnet/aspnetcore/Runtime/9.0.12/aspnetcore-runtime-9.0.12-linux-arm64.tar.gz"
    source = "https://builds.dotnet.microsoft.com/dotnet/aspnetcore/Runtime/9.0.12/aspnetcore-runtime-9.0.12-linux-arm64.tar.gz"
    source-checksum = "sha512:9459fd465ac014188b440e0dd785427e3538224d37578a4734382e2a7069c0d87014eb07e98309386e195b4487536f8d8ccb126f7178f2e2521ac934bf63de6d"
    stacks = ["*"]
    uri = "https://builds.dotnet.microsoft.com/dotnet/aspnetcore/Runtime/9.0.12/aspnetcore-runtime-9.0.12-linux-arm64.tar.gz"
    version = "9.0.12"

  [[metadata.dependencies]]
    arch = "amd64"
    checksum = "sha512:cd01174c52a2ff8107d24eb61c18db44639e4a764b125a7538251d26ad3e4457f5255181c04e6e9aa1d3a4a084dea007152a44777b52e3b43ce0fae8f221a831"
    cpe = "cpe:2.3:a:microsoft:.net:10.0.1:*:*:*:*:*:*:*"
    deprecation_date = "2028-11-14T00:00:00Z"
    id = "dotnet-core-aspnet-runtime"
    licenses = ["MIT", "MIT-0"]
    name = "ASP.NET Core Runtime"
    os = "linux"
    purl = "pkg:generic/dotnet-core-aspnet-runtime@10.0.1?checksum=cd01174c52a2ff8107d24eb61c18db44639e4a764b125a7538251d26ad3e4457f5255181c04e6e9aa1d3a4a084dea007152a44777b52e3b43ce0fae8f221a831&download_url=https://builds.dotnet.microsoft.com/dotnet/aspnetcore/Runtime/10.0.1/aspnetcore-runtime-10.0.1-linux-x64.tar.gz"
    source = "https://builds.dotnet.microsoft.com/dotnet/aspnetcore/Runtime/10.0.1/aspnetcore-runtime-10.0.1-linux-x64.tar.gz"
    source-checksum = "sha512:cd01174c52a2ff8107d24eb61c18db44639e4a764b125a7538251d26ad3e4457f5255181c04e6e9aa1d3a4a084dea007152a44777b52e3b43ce0fae8f221a831"
    stacks = ["*"]
    uri = "https://builds.dotnet.microsoft.com/dotnet/aspnetcore/Runtime/10.0.1/aspnetcore-runtime-10.0.1-linux-x64.tar.gz"
    version = "10.0.1"

  [[metadata.dependencies]]
    arch = "arm64"
    checksum = "sha512:85f2b853bc9506ffd1a086d28df288e9b0bff3eca12900ad8ef459f2ec9d537f9341564dd7a6dfee6534555509af51554c6b9cb16874e31ef141cbcf6eccccf2"
    cpe = "cpe:2.3:a:microsoft:.net:10.0.1:*:*:*:*:*:*:*"
    deprecation_date = "2028-11-14T00:00:00Z"
    id = "dotnet-core-aspnet-runtime"
    licenses = ["MIT", "MIT-0"]
    name = "ASP.NET Core Runtime"
    os = "linux"
    purl = "pkg:generic/dotnet-core-aspnet-runtime@10.0.1?checksum=85f2b853bc9506ffd1a086d28df288e9b0bff3eca12900ad8ef459f2ec9d537f9341564dd7a6dfee6534555509af51554c6b9cb16874e31ef141cbcf6eccccf2&download_url=https://builds.dotnet.microsoft.com/dotnet/aspnetcore/Runtime/10.0.1/aspnetcore-runtime-10.0.1-linux-arm64.tar.gz"
    source = "https://builds.dotnet.microsoft.com/dotnet/aspnetcore/Runtime/10.0.1/aspnetcore-runtime-10.0.1-linux-arm64.tar.gz"
    source-checksum = "sha512:85f2b853bc9506ffd1a086d28df288e9b0bff3eca12900ad8ef459f2ec9d537f9341564dd7a6dfee6534555509af51554c6b9cb16874e31ef141cbcf6eccccf2"
    stacks = ["*"]
    uri = "https://builds.dotnet.microsoft.com/dotnet/aspnetcore/Runtime/10.0.1/aspnetcore-runtime-10.0.1-linux-arm64.tar.gz"
    version = "10.0.1"

  [[metadata.dependencies]]
    arch = "amd64"
    checksum = "sha512:41ecfe6a6ef9e587a58f1336fe667e90585f0bca2227e25d0de9340c634967b180ef8c7c93a61fe390949a9fddc1e656ba717bc132f6947e6e450fcfc4966020"
    cpe = "cpe:2.3:a:microsoft:.net:10.0.2:*:*:*:*:*:*:*"
    deprecation_date = "2028-11-14T00:00:00Z"
    id = "dotnet-core-aspnet-runtime"
    licenses = ["MIT", "MIT-0"]
    name = "ASP.NET Core Runtime"
    os = "linux"
    purl = "pkg:generic/dotnet-core-aspnet-runtime@10.0.2?checksum=41ecfe6a6ef9e587a58f1336fe667e90585f0bca2227e25d0de9340c634967b180ef8c7c93a61fe390949a9fddc1e656ba717bc132f6947e6e450fcfc4966020&download_url=https://builds.dotnet.microsoft.com/dotnet/aspnetcore/Runtime/10.0.2/aspnetcore-runtime-10.0.2-linux-x64.tar.gz"
    source = "https://builds.dotnet.microsoft.com/dotnet/aspnetcore/Runtime/10.0.2/aspnetcore-runtime-10.0.2-linux-x64.tar.gz"
    source-checksum = "sha512:41ecfe6a6ef9e587a58f1336fe667e90585f0bca2227e25d0de9340c634967b180ef8c7c93a61fe390949a9fddc1e656ba717bc132f6947e6e450fcfc4966020"
    stacks = ["*"]
    uri = "https://builds.dotnet.microsoft.com/dotnet/aspnetcore/Runtime/10.0.2/aspnetcore-runtime-10.0.2-linux-x64.tar.gz"
    version = "10.0.2"

  [[metadata.dependencies]]
    arch = "arm64"
    checksum = "sha512:52ec81492d6d4253c00d7f51f12d5fddb10252ce664db020c4a90e4433e7eb7862529737400d5862f6fba41cb2bcf223f802e01d194b82908ce84530b03800b1"
    cpe = "cpe:2.3:a:microsoft:.net:10.0.2:*:*:*:*:*:*:*"
    deprecation_date = "2028-11-14T00:00:00Z"
    id = "dotnet-core-aspnet-runtime"
    licenses = ["MIT", "MIT-0"]
    name = "ASP.NET Core Runtime"
    os = "linux"
    purl = "pkg:generic/dotnet-core-aspnet-runtime@10.0.2?checksum=52ec81492d6d4253c00d7f51f12d5fddb10252ce664db020c4a90e4433e7eb7862529737400d5862f6fba41cb2bcf223f802e01d194b82908ce84530b03800b1&download_url=https://builds.dotnet.microsoft.com/dotnet/aspnetcore/Runtime/10.0.2/aspnetcore-runtime-10.0.2-linux-arm64.tar.gz"
    source = "https://builds.dotnet.microsoft.com/dotnet/aspnetcore/Runtime/10.0.2/aspnetcore-runtime-10.0.2-linux-arm64.tar.gz"
    source-checksum = "sha512:52ec81492d6d4253c00d7f51f12d5fddb10252ce664db020c4a90e4433e7eb7862529737400d5862f6fba41cb2bcf223f802e01d194b82908ce84530b03800b1"
    stacks = ["*"]
    uri = "https://builds.dotnet.microsoft.com/dotnet/aspnetcore/Runtime/10.0.2/aspnetcore-runtime-10.0.2-linux-arm64.tar.gz"
    version = "10.0.2"

  [[metadata.dependency-constraints]]
    constraint = "8.0.*"
    id = "dotnet-core-aspnet-runtime"
    patches = 2

  [[metadata.dependency-constraints]]
    constraint = "9.0.*"
    id = "dotnet-core-aspnet-runtime"
    patches = 2

  [[metadata.dependency-constraints]]
    constraint = "10.0.*"
    id = "dotnet-core-aspnet-runtime"
    patches = 2

[[stacks]]
  id = "*"

[[targets]]
  arch = "amd64"
  os = "linux"

[[targets]]
  arch = "arm64"
  os = "linux"
